/* Feature / module flags controlled by business type configuration. */
enum AppFeature {
  /* Core POS */
  barcodeBilling,
  productGridBilling,
  quickBilling,
  holdResumeInvoice,
  splitPayment,
  creditSale,
  returns,
  exchange,
  refunds,
  coupons,
  offers,

  /* F&B */
  tables,
  floors,
  kot,
  dineIn,
  takeaway,
  parcel,
  userWiseBilling,
  portions,
  modifiers,
  kitchenDepartments,
  waiterAssign,
  mess,

  /* Apparel / variants */
  sizeColorMatrix,
  variants,
  brands,
  fabric,
  serialNumbers,

  /* Retail inventory */
  batchExpiry,
  reorderLevels,
  warehouses,
  stockTransfer,
  purchaseFlow,
  vendors,
  weightUnits,

  /* Hotel */
  rooms,
  roomBooking,
  checkInOut,
  guestLedger,
  roomRestaurantBilling,

  /* CRM / loyalty */
  customers,
  loyalty,
  membership,
  wallet,

  /* Ops */
  multiBranch,
  multiCounter,
  multiWarehouse,
  approvals,
  auditLog,
  expenses,
  reports,
  inventory,
  combos,
  pharmacySchedule,
}

extension AppFeatureX on AppFeature {
  String get id => name;

  String get label => switch (this) {
    AppFeature.barcodeBilling => 'Barcode Billing',
    AppFeature.productGridBilling => 'Product Grid',
    AppFeature.quickBilling => 'Quick Billing',
    AppFeature.holdResumeInvoice => 'Hold / Resume',
    AppFeature.splitPayment => 'Split Payment',
    AppFeature.creditSale => 'Credit Sale',
    AppFeature.returns => 'Returns',
    AppFeature.exchange => 'Exchange',
    AppFeature.refunds => 'Refunds',
    AppFeature.coupons => 'Coupons',
    AppFeature.offers => 'Offers',
    AppFeature.tables => 'Tables',
    AppFeature.floors => 'Floors',
    AppFeature.kot => 'KOT',
    AppFeature.dineIn => 'Dine-in',
    AppFeature.takeaway => 'Takeaway',
    AppFeature.parcel => 'Parcel / Delivery',
    AppFeature.userWiseBilling => 'User-wise Billing',
    AppFeature.portions => 'Portions',
    AppFeature.modifiers => 'Modifiers / Add-ons',
    AppFeature.kitchenDepartments => 'Kitchen Departments',
    AppFeature.waiterAssign => 'Waiter',
    AppFeature.mess => 'Mess',
    AppFeature.sizeColorMatrix => 'Size / Color Matrix',
    AppFeature.variants => 'Variants',
    AppFeature.brands => 'Brands',
    AppFeature.fabric => 'Fabric / Material',
    AppFeature.serialNumbers => 'Serial Numbers',
    AppFeature.batchExpiry => 'Batch / Expiry',
    AppFeature.reorderLevels => 'Reorder Levels',
    AppFeature.warehouses => 'Warehouses',
    AppFeature.stockTransfer => 'Stock Transfer',
    AppFeature.purchaseFlow => 'Purchase',
    AppFeature.vendors => 'Vendors',
    AppFeature.weightUnits => 'Weight / Units',
    AppFeature.rooms => 'Rooms',
    AppFeature.roomBooking => 'Room Booking',
    AppFeature.checkInOut => 'Check-in / Check-out',
    AppFeature.guestLedger => 'Guest Ledger',
    AppFeature.roomRestaurantBilling => 'Room + Restaurant Billing',
    AppFeature.customers => 'Customers',
    AppFeature.loyalty => 'Loyalty',
    AppFeature.membership => 'Membership',
    AppFeature.wallet => 'Wallet',
    AppFeature.multiBranch => 'Multi-branch',
    AppFeature.multiCounter => 'Multi-counter',
    AppFeature.multiWarehouse => 'Multi-warehouse',
    AppFeature.approvals => 'Approvals',
    AppFeature.auditLog => 'Audit Log',
    AppFeature.expenses => 'Expenses',
    AppFeature.reports => 'Reports',
    AppFeature.inventory => 'Inventory',
    AppFeature.combos => 'Combos / Bundles',
    AppFeature.pharmacySchedule => 'Pharmacy Schedule',
  };
}
