/// Image paths under `assets/images`.
abstract final class AppAssets {
  static const png = 'assets/images/png';
  static const svg = 'assets/images/svg';

  // —— PNG ——
  static const appLogo = '$png/app_logo.png';
  static const splashBranding = '$png/splash_branding.png';
  static const yourLogoHere = '$png/your_logo_here.png';
  static const product = '$png/product.png';
  static const stock = '$png/stock.png';
  static const mess = '$png/mess.png';
  static const invoice = '$png/invoice.png';
  static const expense = '$png/expense.png';
  static const settings = '$png/settings.png';
  static const accounting = '$png/accounting.png';
  static const upi = '$png/upi.png';
  static const add = '$png/add.png';
  static const addProfile = '$png/add_profile.png';
  static const adminMenu = '$png/admin_menu_icon.png';
  static const bank = '$png/bank.png';
  static const camera = '$png/camera.png';
  static const picture = '$png/picture.png';
  static const appPin = '$png/app_pin.png';
  static const rupeePending = '$png/rupee_pending.png';
  static const megaphones = '$png/megaphones.png';
  static const shareHero = '$png/img_share_header_hero.png';
  static const shareMegaphone = '$png/img_share_megaphone.png';
  static const sharePhoneQr = '$png/img_share_phone_qr.png';
  static const shareGrowthBadge = '$png/img_share_growth_badge.png';

  /// Default thermal / bill logo when shop file is missing.
  static const receiptLogo = yourLogoHere;

  // —— SVG backgrounds ——
  static const svgSplashWave = '$svg/bg_splash_wave.svg';
  static const svgLoginCard = '$svg/bg_login_card.svg';
  static const svgLoginGradientButton = '$svg/bg_login_gradient_button.svg';
  static const svgMpinIconCircle = '$svg/bg_mpin_icon_circle.svg';
  static const svgMpinBoxEmpty = '$svg/bg_mpin_pin_box_empty.svg';
  static const svgMpinBoxFilled = '$svg/bg_mpin_pin_box_filled.svg';
  static const svgHomeHeader = '$svg/bg_home_header_card.svg';
  static const svgHomeWave = '$svg/bg_home_wave_footer.svg';
  static const svgHomeSettingsBtn = '$svg/bg_home_settings_btn.svg';
  static const svgHomeStatusPill = '$svg/bg_home_status_pill.svg';
  static const svgHomePrinterPill = '$svg/bg_home_printer_status_pill.svg';
  static const svgHomeSyncCard = '$svg/bg_home_sync_card.svg';
  static const svgKpiCardBlue = '$svg/bg_kpi_card_blue.svg';
  static const svgKpiCardGreen = '$svg/bg_kpi_card_green.svg';
  static const svgKpiCardOrange = '$svg/bg_kpi_card_orange.svg';
  static const svgKpiCardPurple = '$svg/bg_kpi_card_purple.svg';
  static const svgKpiWaveBlue = '$svg/bg_kpi_wave_blue.svg';
  static const svgKpiWaveGreen = '$svg/bg_kpi_wave_green.svg';
  static const svgCard = '$svg/bg_card.svg';
  static const svgInput = '$svg/bg_input.svg';
  static const svgHeader = '$svg/bg_header.svg';
  static const svgHeaderBack = '$svg/bg_header_back_btn.svg';
  static const svgButtonPrimary = '$svg/bg_button_primary.svg';
  static const svgButtonOutline = '$svg/bg_button_outline.svg';
  static const svgFab = '$svg/bg_fab_primary.svg';
  static const svgBottomSheet = '$svg/bg_bottom_sheet_panel.svg';
  static const svgNotificationBadge = '$svg/bg_notification_badge.svg';

  // —— SVG icons ——
  static const svgKey = '$svg/ic_key.svg';
  static const svgLock = '$svg/ic_lock.svg';
  static const svgLockOpen = '$svg/ic_lock_open.svg';
  static const svgHome = '$svg/ic_home.svg';
  static const svgSettings = '$svg/ic_settings.svg';
  static const svgSearch = '$svg/ic_search.svg';
  static const svgNotification = '$svg/ic_stat_notification.svg';
  static const svgPrint = '$svg/ic_print.svg';
  static const svgShare = '$svg/ic_share.svg';
  static const svgSharePeople = '$svg/ic_share_people.svg';
  static const svgShareBenefitGrow = '$svg/ic_share_benefit_grow.svg';
  static const svgShareBenefitTime = '$svg/ic_share_benefit_time.svg';
  static const svgShareBenefitBilling = '$svg/ic_share_benefit_billing.svg';
  static const svgBack = '$svg/ic_back.svg';
  static const svgClose = '$svg/ic_close.svg';
  static const svgAdd = '$svg/ic_add.svg';
  static const svgEdit = '$svg/ic_edit.svg';
  static const svgDelete = '$svg/ic_delete.svg';
  static const svgCheck = '$svg/ic_check.svg';
  static const svgInfo = '$svg/ic_info.svg';
  static const svgWarning = '$svg/ic_warning.svg';
  static const svgPerson = '$svg/ic_person.svg';
  static const svgPhone = '$svg/ic_phone.svg';
  static const svgCart = '$svg/ic_cart.svg';
  static const svgQr = '$svg/ic_qr_code.svg';
  static const svgScan = '$svg/ic_qr_code.svg';
  static const svgCloudSync = '$svg/baseline_cloud_sync_24.svg';
  static const svgCloudDownload = '$svg/ic_cloud_download.svg';
  static const svgCloudUpload = '$svg/ic_cloud_upload.svg';
  static const svgLogout = '$svg/ic_logout.svg';
  static const svgMic = '$svg/ic_mic.svg';
  static const svgFilter = '$svg/ic_filter.svg';
  static const svgCalendar = '$svg/ic_calendar.svg';
  static const svgClock = '$svg/ic_clock.svg';
  static const svgReceipt = '$svg/ic_receipt.svg';
  static const svgInventory = '$svg/ic_inventory.svg';
  static const svgExpense = '$svg/ic_expense.svg';
  static const svgCategory = '$svg/ic_category.svg';
  static const svgBusiness = '$svg/ic_business.svg';
  static const svgTable = '$svg/baseline_table_bar_24.svg';
  static const svgTableAlt = '$svg/ic_table.svg';
  static const svgTakeaway = '$svg/ic_takeaway.svg';
  static const svgStore = '$svg/ic_store.svg';
  static const svgTrendingUp = '$svg/ic_trending_up.svg';
  static const svgTrendingDown = '$svg/ic_trending_down.svg';
  static const svgBill = '$svg/baseline_bill.svg';
  static const svgWalk = '$svg/baseline_directions_walk_24.svg';
  static const svgEmpty = '$svg/ic_folder.svg';
  static const svgRefresh = '$svg/ic_refresh.svg';
  static const svgArrowForward = '$svg/ic_arrow_forward.svg';
  static const svgHide = '$svg/ic_hide.svg';
  static const svgPin = '$svg/ic_pin.svg';
  static const svgLocation = '$svg/ic_location_pin.svg';
  static const svgFood = '$svg/ic_food_placeholder.svg';
  static const svgProductsTab = '$svg/ic_products_tab.svg';
  static const svgHeadset = '$svg/ic_headset.svg';
  static const svgCopy = '$svg/ic_copy.svg';
  static const svgAttach = '$svg/ic_attach.svg';
  static const svgStar = '$svg/baseline_star_half_24.svg';
  static const svgChevron = '$svg/ic_chevron_right.svg';
  static const svgPlayStore = '$svg/ic_play_store.svg';
  static const svgGooglePlayBadge = '$svg/bg_google_play_badge.svg';

  // —— About Us ——
  static const svgAboutWeb = '$svg/ic_about_web.svg';
  static const svgAboutEmail = '$svg/ic_about_email.svg';
  static const svgAboutPhone = '$svg/ic_about_phone.svg';
  static const svgAboutIconCircle = '$svg/bg_about_icon_circle.svg';
  static const svgAboutVersionBadge = '$svg/bg_about_version_badge.svg';
  static const svgAboutFeatureBlue = '$svg/bg_about_feature_tile_blue.svg';
  static const svgAboutFeatureGreen = '$svg/bg_about_feature_tile_green.svg';
  static const svgAboutFeatureOrange = '$svg/bg_about_feature_tile_orange.svg';
  static const svgAboutFeaturePurple = '$svg/bg_about_feature_tile_purple.svg';
  static const svgAboutFeaturePink = '$svg/bg_about_feature_tile_pink.svg';
  static const svgAboutDisclaimerCard = '$svg/bg_about_disclaimer_card.svg';
  static const svgAboutDeveloperIcon = '$svg/bg_about_developer_icon.svg';
}

